### ISSUE TITLE
Can't delete?

### ISSUE THREAD

**Issue by markpundsack** [heroku/heroku-attachable-resources#21]
I'm trying to destroy a database, but it complains that I can't destroy the last attachment. Why not? It turns out it's because it's been attached somewhere else and I can't delete it until that other attachment has been deleted, but the error message is completely useless for this. How about "Cannot destroy resource while it is attached elsewhere" and then list where else it is attached?

$ h addons:remove gazing-patiently-2570 -a dashboard-mk

 !    WARNING: Destructive Action
 !    This command will affect the app: dashboard-mk
 !    To proceed, type "dashboard-mk" or re-run this command with --confirm dashboard-mk

> dashboard-mk
> removing gazing-patiently-2570 from dashboard-mk... failed
>  !    Cannot destroy last attachment to billing app for resource gazing-patiently-2570

**Comment by kriskova** [comment]
Same here.

Wanted to change DATABASE_URL to an external postgres and got the same error:

```
Setting config vars and restarting xxx ... failed
 !    Cannot destroy last attachment to billing app for resource xxx...
```

**Comment by tomj** [comment]
From [Heroku](https://devcenter.heroku.com/articles/managing-add-ons)

> Previously to destroy an add-on you could use the command addons:remove. That command is now deprecated in favor of the destroy command.

**Comment by TalosThoren** [comment]
I'm having this same issue when attempting to run `heroku addons:detach`. I'm also receiving `Resource postgresql-blahblah-99999 must be detached from all other apps before deprovisioning.` when using `addons:destroy`.

When attempting to delete my hobby-dev plan postgresDB from the browser interface I receive an error that claims the Heroku team has been alerted, and that I should wait and try again.

waiting a couple hours did not resolve the issue. Why does this happen? There is nothing in the documentation to indicate that this is expected nor normal behavior.

**Comment by ransombriggs** [comment]
@TalosThoren sorry that you have received this error, could you please file a support ticket at https://heroku.support so we can help resolve this issue?  This repo has been deprecated and going through the support tool will help us better track on which addon that you are having the issue.
